POST http://localhost:3000/register
Content-Type:application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtpbmciLCJpYXQiOjE3MjMxMzc3NDV9.lAdi9GoJaDSChDk6ziHRFd8cl3tb03ZUdahM4V2ZOwk

{
    "username":"raina",
    "email":"raina@123",
    "password":"raina"
}